### ISSUE TITLE
Use readthedocs for documentation?

### ISSUE THREAD

**Issue by skirpichev** [fredrik-johansson/mpmath#299]
Here is my test setup: http://mpmath.readthedocs.org/
It works from my fork of mpmath (to get docs for several versions [you need tags](https://docs.readthedocs.org/en/latest/versions.html)).

How this looks cf. http://mpmath.org/doc/, what do you think?

**Comment by skirpichev** [comment]
> I would obviously add a link to the readthedocs version, particularly seeing as it could track the git master automatically.

Ok.  Can you please add git tags, at least for several latest versions?  See my fork:
https://github.com/skirpichev/mpmath
https://github.com/skirpichev/mpmath/tags

Also, I think I should add you as a maintainer for http://mpmath.readthedocs.org/.  Do you have account on RTD?

> I think the readthedocs style has too low contrast, particularly the code boxes and the sidebar.

I'll try to fix this.

> it would really be nicer to switch to MathJax rendering

It does work for me locally.  I'll provide patch.

**Comment by skirpichev** [comment]
>>    I think the readthedocs style has too low contrast, particularly the code boxes and the sidebar.
>
> I'll try to fix this.

Ok, for now I just use default sphinx theme, see #314.  Is this ok?

**Comment by fredrik-johansson** [comment]
I'm ok with linking to readthedocs (but I will keep a copy of the documentation on mpmath.org).

**Comment by skirpichev** [comment]
ok, thank you for your time..

You can remove me from maintainers on RTD (I can't do this myself, unfortunately).

**Comment by fredrik-johansson** [comment]
Is there a reason why you don't want to remain as a maintainer?

**Comment by skirpichev** [comment]
Before, I expect you are not just against RTD without technical reasons.  I.e. you don't like style or something similar, that could be fixed in principle.  As I said before, the idea was to host actual docs, not a mirror.

**Comment by skirpichev** [comment]
@fredrik-johansson, it seems you wont use the https://readthedocs.org/projects/mpmath/ to provide docs.  I'll remove this project in 2 weeks.  Let me know, if you disagree.
