### ISSUE TITLE
incomplete gamma value wrong

### ISSUE THREAD

**Issue by rwst** [fredrik-johansson/mpmath#301]
This is from within Sage with 
```
sage: import mpmath
sage: mpmath.gammainc(-1,-1)
mpc(real='-0.82316401210310852', imag='-3.1415926535897931')
```
Same with Sympy live. However, Pari and Wolfram say it's +pi imaginary not minus.

Came up in http://trac.sagemath.org/ticket/16697#comment:30

**Comment by cimatosa** [comment]
Hi, I don't think it actually has a branch cut. No matter from where you approach the point (-1, -1) the imaginary part will always approach pi, even for any second argument. At least numerically I could verify that.

```
z = mp.mpf('-1')
eps_re = mp.mpf('0.01')
eps_im = mp.mpf('0.01')

f0 = lambda a: mp.im(mp.gammainc(z, a))
f1 = lambda a: mp.im(mp.gammainc(z+eps_re, a))
f2 = lambda a: mp.im(mp.gammainc(z-eps_re, a))
f3 = lambda a: mp.im(mp.gammainc(z+1j*eps_im, a))
f4 = lambda a: mp.im(mp.gammainc(z-1j*eps_im, a))

mp.plot([f0, f1,f2,f3,f4], [-2,-1])
```

So in terms of continuation the incomplete gamma function should return for its imaginary part +pi for all a < 0 and z=-1.

**Comment by fredrik-johansson** [comment]
The branch cut is with respect to a, not with respect to z.

**Comment by cimatosa** [comment]
But when varying a I don't see any discontinuities. Am I missing something?

**Comment by fredrik-johansson** [comment]
>>> gammainc(-1, -1 + 1e-20j)
    (-0.823164012103109 + 3.14159265358979j)
    >>> gammainc(-1, -1 - 1e-20j)
    (-0.823164012103109 - 3.14159265358979j)

**Comment by cimatosa** [comment]
ok, sorry for bothering around. I was not aware of the fact, that actually 'a' may also be complex.

**Comment by fredrik-johansson** [comment]
Well, thanks for reminding me about the issue! I just fixed the problem.

The code in question is terrifying; I bet it has more bugs...
