### ISSUE TITLE
Incorrect oscillatory quadrature calculation

### ISSUE THREAD

**Issue by FelisPhasma** [fredrik-johansson/mpmath#309]
I am getting an incorrect calculation when computing an oscillatory integral from 1 to infinity using `quadosc`.
The equation is `x^(1/x) * cos(pi*x)`. Here is my code:
```
from mpmath import *
mp.dps = 35; mp.pretty = True
f = lambda x: root(x, x) * cos(pi * x)
print quadosc(f, [1,inf], period=2)
```
I am getting `0.15754208208519192532792126679668005`(mpmath calculation) When I should be getting a value closer to `0.0707760378979824661405118035873`(C++ calculation).

Either I've made a mistake, in which case I am very sorry for creating this issue, or the calculation is just incorrect.

Cheers!

**Comment by fredrik-johansson** [comment]
It appears that root(x,x) computes root(x,int(x)).

Using f = lambda x: x**(1/x) * cospi(x) gives the expected answer

    >>> quadosc(lambda x: x**(1/x) * cospi(x), [1,inf], period=2)
    0.070776039311528803539528021830282001365754696203363

**Comment by skirpichev** [comment]
> It appears that root(x,x) computes root(x,int(x)).

Nothing is wrong here (it's documented in mpmath.root).  Why this bug is open?

**Comment by FelisPhasma** [comment]
Sorry... As I said, "Either I've made a mistake, in which case I am very sorry for creating this issue, or the calculation is just incorrect". As I have done something wrong, I see it fit to close the bug. Thank for your time!

**Comment by fredrik-johansson** [comment]
By the way, note that this integral is not absolutely convergent.

Whether the interpretation of quadosc makes sense depends on the application.

**Comment by FelisPhasma** [comment]
True, this integral doesn't converge. `quadosc` seems to be able to make sense out of `x^(1/x) * cos(pi*x)`, but it doesn't appear to be able to make sense out of `x^(1/x) * sin(pi*x)`. Thanks again!
