### ISSUE TITLE
betainc with complex arguments

### ISSUE THREAD

**Issue by aonghus-mor** [fredrik-johansson/mpmath#310]
I've been using mpmath.betainc(a,b,0,z) where a is complex, but z is real, 0<z<1.  I need the case b=0, but this fails, even though there is no cut: the function has the same value either side of b=0.  I suspect this is related to the fact that beta(a,0) should diverge.
I also tried using the fp version, but this doesn't seem to cope properly with complex arguments. It gives a complex result, with a zero imaginary part.
I guess the issue is really with the underlying hypergeometric function.

**Comment by fredrik-johansson** [comment]
Could you give a concrete example of values a, b, z and the value you expect for betainc(a,b,0,z) ?

**Comment by aonghus-mor** [comment]
I’ve tried this on a different machine and the problem went away.  I need to do some more work to find out why the difference.   A different version of something, I suspect.

However, the issue I mentioned with the fp version is still there.   I note that the basic scipy version of betainc or hyp2F1 doesn’t handle complex arguments at all.

Regards

Angus MacKinnon

**Comment by fredrik-johansson** [comment]
Closing this since no further information has been provided.
