### ISSUE TITLE
fraction precision problems mpmath-0.19

### ISSUE THREAD

**Issue by hmilan** [fredrik-johansson/mpmath#322]
I am trying to calculate the following fraction for example, but it is not improving the result if continued
bc works OK

import mpmath
mpmath.mp.dps=100
mpmath.mpf('1.0')/(1+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/(2+1/2))))))))))))))))))))))))))))))))))
this should approach toward mpmath.sqrt(2)/2 but it stops improving after about 16 correct digits. I have no idea how to make it work correctly ??

**Comment by fredrik-johansson** [comment]
You are computing the fraction as a Python float. It is the inner 1 that should be mpmath.mpf(1), not the outer one.

**Comment by hmilan** [comment]
I was mislead by the examples like this: mpmath.mpf('1.0')/6  in the mpmath documentation. Sorry about that. Replacing every 1 and 2 by mpf() works to any number of digits, or at least upto 500 that I tested :-)
