### ISSUE TITLE
Conversion to float does not round correctly

### ISSUE THREAD

**Issue by stephan-tolksdorf** [fredrik-johansson/mpmath#324]
I'd expect the built-in conversion to a double precision `float` to round to the nearest number, but it doesn't:

```
>>> import mpmath
>>> mpmath.libmp.BACKEND
'gmpy'
>>> from mpmath import mp
>>> mp.prec = 64
>>> x = mp.one + 7*2**-54
>>> float(x) == float(mp.mpf(x, prec = 53))
False
>>> print(x, mp.mpf(float(x)), mp.mpf(x, prec = 53))
1.00000000000000039 1.00000000000000022 1.00000000000000044
>>> print(x, float(x), float(mp.mpf(x, prec = 53)))
1.00000000000000039 1.0000000000000002 1.0000000000000004
```

BTW, thanks a lot for your work on mpmath! The library has been very helpful for my work.

**Comment by fredrik-johansson** [comment]
Thanks for reporting this issue. The current behavior of rounding down is a tiny bit faster, but this shouldn't matter. I just changed it to round to the context rounding mode (nearest by default) instead.

**Comment by stephan-tolksdorf** [comment]
Thanks a lot!

**Comment by fredrik-johansson** [comment]
Weird; I just noticed that the test code is failing on Travis. I really have no clue why; it works just fine for me.

**Comment by fredrik-johansson** [comment]
Fixed.
