### ISSUE TITLE
visualization test fails with latest pylab from pypi

### ISSUE THREAD

**Issue by difranco** [fredrik-johansson/mpmath#326]
using pylab-0.1.3-py2.py3-none-any.whl
seems maybe like this should be imported from matplotlib rather than pylab directly

test_visualization
    axes                      
TEST FAILED!

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpmath/tests/runtests.py", line 126, in testit
    module.__dict__[f]()
  File "/usr/local/lib/python3.5/dist-packages/mpmath/tests/test_visualization.py", line 20, in test_axes
    fig = pylab.figure()
AttributeError: module 'pylab' has no attribute 'figure'
ok        0.0483229 s

finished tests in 13.05 seconds

**Comment by fredrik-johansson** [comment]
I think this is caused by installing another "pylab" package besides matplotlib. This seems to have been removed from pypi now (https://pypi.python.org/pypi/pylab/0.1.3) to avoid confusion.
