### ISSUE TITLE
Obsoleted section in setup.html

### ISSUE THREAD

**Issue by skirpichev** [fredrik-johansson/mpmath#328]
Both [here](http://mpmath.org/doc/current/setup.html#current-development-version) and [here](http://mpmath.readthedocs.io/en/latest/setup.html#current-development-version).  I doubt that any svn instructions are relevant now on github...

**Comment by fredrik-johansson** [comment]
Fixed in 15e871e9075a. Thanks for reporting. I bet there's even more obsolete stuff in the docs.
