### ISSUE TITLE
Python 3.x/2.x incompatibility issue in gammazeta.py

### ISSUE THREAD

**Issue by ekuznetsov139** [fredrik-johansson/mpmath#330]
gammazeta.py (function mpc_zetasum) contains the following code:

    have_derivatives = derivatives != [0]
    (...)

In some scenarios, it is being called with "derivatives" equal to range(0,1). The intended behavior is for "have_derivatives" to evaluate to False in this case.

However:

 Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
> x=range(0,1)
> y=[0]
> x==y

True

> 

Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
> x=range(0,1)
> y=[0]
> x==y

False

> 

The effect is that an optimized function (zetasum_sieved) is not used in 3.x.

**Comment by ekuznetsov139** [comment]
While we're at it, I suggest a small fix.

The first if() in mpc_zetasum currently reads

`if a > 0 and n > ZETASUM_SIEVE_CUTOFF and not have_derivatives and not reflect:`

I would modify it to:

`if a > 0 and n > ZETASUM_SIEVE_CUTOFF and not have_derivatives and not reflect and (n<4e7 or sys.maxsize>2**32):`

(You'd need to add "import sys" in the same file.)

The reason is that current code fails in 32-bit Python if n is sufficiently large. For example, attempting to calculate zeta(0.5+j*1e17) or siegelz(1e17) results in MemoryError being thrown, since zetasum_sieved attempts to allocate a list of length n = sqrt(1e17/2pi) \approx 1.2e8, and 32-bit Python does not have enough memory for that. Avoiding zetasum_sieved path in this scenario allows the calculation to complete (though perhaps to take longer than it would've in a 64-bit interpreter.)

**Comment by fredrik-johansson** [comment]
These changes seem OK. Do you want to make a pull request?

**Comment by fredrik-johansson** [comment]
Fixed (hopefully).
