### ISSUE TITLE
Wrong result for modified Bessel function besseli

### ISSUE THREAD

**Issue by michael-hartmann** [fredrik-johansson/mpmath#331]
Dear mpmath team,

I stumbled over a problem regarding the modified Bessel function besseli. The result from besseli depends strongly on the precision mpmath.mp.dps. Here is a brief example:
```
import mpmath as mp

nu = mp.mpf(91.5)
x  = mp.mpf(24.7708)

v1 = mp.besseli(nu,x)
print(v1)

mp.mp.dps = 50

v2 = mp.besseli(nu,x)
print(v2)
```

This outputs:
```
4.00830632138674e-41
1.8625765211549663824095874757588999702112646063871e-20
```

According to Mathematica (Wolfram Alpha) the correct result is 4.0083063213867e-41. This means that the first result is correct, while the result for dps=50 is wrong. The result strongly depends on dps:
```
dps=10, besselI(nu,x)=4.00831e-41 (correct)
dps=20, besselI(nu,x)=1.18055e+10 (wrong)
dps=30, besselI(nu,x)=-0.485061 (wrong, even wrong sign)
dps=40, besselI(nu,x)=-1.3176e-10 (wrong, even wrong sign)
dps=50, besselI(nu,x)=1.86258e-20 (wrong)
dps=60, besselI(nu,x)=-1.40303e-30 (wrong, even wrong sign)
dps=70, besselI(nu,x)=7.4243e-42 (wrong)
dps=80, besselI(nu,x)=4.00831e-41 (correct)
dps=90, besselI(nu,x)=4.00831e-41 (correct)
```

If I understand the code correct the hypergeometric function is used to calculate the modified Bessel function. This might imply that this bug also affects other functions.

I'm using an Anaconda distribution and mpmath 0.19.
```
Python 3.5.2 |Anaconda 2.5.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpmath
>>> mpmath.__version__
'0.19'
```

Thank you for your help! :)

**Comment by michael-hartmann** [comment]
Hello,

Updating my Anaconda to version 4.2.0 did not solve the problem. Also, I can reproduce the problem on Debian 3.4.2 which uses Python 3.4.2 and mpmath version 0.19.

However, I found a workaround that works for me: Adding the option force_series=True gives the correct results:
    mp.besseli(nu,x, force_series=True)
Please note that force_series=True is an option of hypercomb and not a documented option of besseli. This also shows that the problem is in the function hypercomb.

As mpmath is an arbitrary precision library, I still think this is a serious bug, because standard options yield wrong (very wrong!) results.

Thank you for your help. :)

--Michael

**Comment by fredrik-johansson** [comment]
There was no cancellation detection in place when adding the two functions that make up the asymptotic expansion of hyp0f1.

Turns out there was a todo comment in the code to fix this! Thanks a lot for the bug report.

**Comment by michael-hartmann** [comment]
Thank you! :)
