### ISSUE TITLE
Bug: acot(0) ZeroDivisionError

### ISSUE THREAD

**Issue by UpmostScarab** [fredrik-johansson/mpmath#335]
Function acot(0), acot(-0) and with floats gives ZeroDivisionError instead of pi/2. I first encountered this issue using sympy:
https://github.com/sympy/sympy/issues/11809

**Comment by fredrik-johansson** [comment]
Fixed. Thanks. (Note that acot(0) and acot(-0) are the same in mpmath since its zero is unsigned.)
