### ISSUE TITLE
[Python 3.5] NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by KristianOellegaard** [fredrik-johansson/mpmath#344]
Hi there,

I'm not sure why this happens, but on my python 3.5 install on OS X you use the following code to detect python version:

mpmath/libmp/backend.py, line 36
```python
try:
    xrange
    python3 = False
except NameError:
    python3 = True
```

but it turns out, it doesn't work as expected on my python 3.5:

```python
try:
    xrange
    python3 = False
except NameError:
    python3 = True
print("is python3", python3)
```
```
is python3 False
```

I'm really no python3 expect, but below you use:
```python
if sys.version >= "3.2":
```

Could this or some other way of detecting python3 be preferable?

(for the record)
```
Python 3.5.2 (default, Oct 11 2016, 04:59:56)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> xrange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'xrange' is not defined
```

**Comment by derekrollend** [comment]
@KristianOellegaard I've just seen the same issue.  In my case, pyqtgraph (v 0.9.10) was redefining `xrange` somewhere before I imported mpmath, so this check for `xrange` didn't fail.  Upgrading to pyqtgraph v 0.10.0 fixed this for me, but try narrowing down which libraries are imported before mpmath to determine where `xrange` might be redefined.

**Comment by abrys** [comment]
We where also having this issue. Seems like something caused xrange to be redefined when running some unittests (probably nose). A small change to the code seems to have resolved this.
