### ISSUE TITLE
Incorrect conversion of binary precision to dps

### ISSUE THREAD

**Issue by ArifAhmed1995** [fredrik-johansson/mpmath#346]
I wanted to ask this on gitter/IRC but was unable to find such a channel for mpmath.

https://en.wikipedia.org/wiki/Floating_point#Internal_representation

We can see that for float16, corresponding decimal digits is `~3.3`.
But `prec_to_dps(10)` yields `2`. Shouldn't it be atleast `3` ?

Likewise shouldn't we get `7`,`19` and `34` for binary precision `23`,`64` and `112` respectively ?

**Comment by fredrik-johansson** [comment]
The purpose of `dps_to_prec` is to compute a number of bits sufficient to represent a number of decimals, and `prec_to_dps` is the inverse of this operation. So `dps_to_prec` computes a slight overestimate and `prec_to_dps` accordingly computes a slight underestimate.

The function you want which computes an overestimate in the other direction is `repr_dps`.

**Comment by ArifAhmed1995** [comment]
That clears it up !
