### ISSUE TITLE
error in subtraction of floats?

### ISSUE THREAD

**Issue by KiefAtGitHub** [fredrik-johansson/mpmath#347]
Please consider the following small code snippet I have executed using mpmath version 0.19:

```
from mpmath import *
mp.dps = 35
mp.pretty = True

pi_red=pi-mpf(1e-10)
print(pi)
print(pi_red)
```

As excepted _pi_ and _pi_red_ differ at the 10th digit. However, they also differ starting from the 26th digit. Is this a bug or do I miss something here?

**Comment by asmeurer** [comment]
This is likely due to the inexactness of the float literal used to create 1e-10. Float literals are parsed by Python and always have 15 digits of precision, regardless of the mpmath dps. Use `mpf("1e-10")` instead.

**Comment by KiefAtGitHub** [comment]
Thank you very much! Works perfectly now.
