### ISSUE TITLE
Inconsistency in hyper() evaluation with "eliminate" keyword enabled

### ISSUE THREAD

**Issue by skirpichev** [fredrik-johansson/mpmath#349]
Lets take an example:
```python
In [6]: mpmath.__version__
Out[6]: '0.19'

In [7]: mpmath.hyper((-1, 1), (-1,), 2)
Out[7]: mpf('-1.0')

In [8]: mpmath.hyper((-1, 1), (-1,), 2, eliminate=False)
Out[8]: mpf('3.0')
```

Second result also equivalent to the Mathematica output:
```
In[1]:= HypergeometricPFQ[{-1, 1}, {-1}, 2]

Out[1]= 3
```

@fredrik-johansson, please correct me, but I believe the result must be same with or without eliminating common parameters.  Is that wrong?

This seems to be an issue for SymPy and Diofant.  See sympy/sympy#10531 (real technical discussion was started only [here](https://github.com/sympy/sympy/pull/10531#issuecomment-281806140)) and diofant/diofant#446.

**Comment by fredrik-johansson** [comment]
This is the very purpose of "eliminate" option. Eliminating common parameters is only unambiguous when the parameters are not nonpositive integers. At nonpositive integers, there are two possible interpretations, and mpmath allows you to choose.

Note that Mathematica is inconsistent with itself about which rule to use:

    In[1]:= HypergeometricPFQ[{-1, 1}, {-1}, 2]                                    
    Out[1]= 3
    In[2]:= HypergeometricPFQ[{a, 1}, {a}, 2] /. a -> -1                           
    Out[2]= -1

**Comment by fredrik-johansson** [comment]
> @fredrik-johansson, this seems to be very hackish way of choosing different hyper() definitions.

I don't see what is hackish about it.

> In this case, shouldn't ``eliminate=False`` - be default?

It would probably be fine to change it, though in rare cases it will break compatibility. There are some functions like Jacobi and Gegenbauer polynomials, incomplete beta function, etc. where one would have to check that the expected results are obtained.

It was made default for performance reasons, but it could be changed to eliminate only safe parameters by default, with eliminate=True/False simply controlling elimination of nonpositive integers. Or maybe there should be a completely separate flag for nonpositive integers.

> You also have a documentation issue at least. (eliminate kwarg is not documented in docstring).

True.

**Comment by skirpichev** [comment]
FYI: it seems for me that @fredrik-johansson was positive about technical changes in #350, related to this bug.  Anyone willing to fix this issue?

**Comment by fredrik-johansson** [comment]
Fixed in 9bcd6d4b73f6da45beb9c2ae7771a722ba6a4dbd

**Comment by skirpichev** [comment]
I don't see a regression test, but it seems this should be closed?

```
>>> import mpmath
>>> mpmath.hyper((-1, 1), (-1,), 2)
mpf('3.0')
>>> mpmath.__version__
'0.20-git'
```

**Comment by fredrik-johansson** [comment]
Yes, the existing hyp2f1 tests already checked the same thing.
