### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by symbolique** [fredrik-johansson/mpmath#357]
Version 0.19 was released 3 years ago on June 10, 2014. Some important fixes have been made since, such as #324. Would you consider making a new release?

**Comment by fredrik-johansson** [comment]
Absolutely. I have other things to take care of first, but I'm planning to do this by September.

**Comment by paulmasson** [comment]
September is here...

**Comment by fredrik-johansson** [comment]
Well, are there any outstanding issues blocking a release right now?

**Comment by paulmasson** [comment]
Not to my knowledge. New release, please!
