### ISSUE TITLE
feature request: expose tridiag_eigen

### ISSUE THREAD

**Issue by nschloe** [fredrik-johansson/mpmath#366]
I need to solve a number of real triadiagonal eigen problems and would like to use mpmath's `tridiag_eigen` for it. Any chance for making it accessible?

**Comment by fredrik-johansson** [comment]
Doesn't this work?

    from mpmath.matrices.eigen_symmetric import tridiag_eigen
    tridiag_eigen(mp, ...)

**Comment by nschloe** [comment]
It does, thanks.
