### ISSUE TITLE
Update version on PyPI

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/mpmath#370]
I have no idea how to get a new version onto PyPI. The setup.py upload is deprecated, the web interface gives me an error message, and I can't run twine because of some obscure dependency version conflict. I'd be happy if someone else could just take over maintenance of the project on PyPI.

**Comment by skirpichev** [comment]
I guess, this could be closed: based on sympy maillist thread, you are figured out how to update things on pypi.  (BTW, for the Diofant project I use deployment with travis-ci to automate these things.)

**Comment by fredrik-johansson** [comment]
Indeed.
