### ISSUE TITLE
http://mpmath.org/ is outdated

### ISSUE THREAD

**Issue by skirpichev** [fredrik-johansson/mpmath#371]
It mention 0.19 as "the latest version".  Also, the function gallery is missing, maybe there are more broken links.

**Comment by fredrik-johansson** [comment]
Where does it say that 0.19 is the latest version? I agree that the broken links need to be fixed.

**Comment by skirpichev** [comment]
E.g. section "Downloads, source code, development".  Starts with "The latest version is 0.19, released 2014-06-10."

**Comment by fredrik-johansson** [comment]
I guess you have an old version of the page in your browser cache? I updated it when I released the new version.

**Comment by skirpichev** [comment]
> I guess you have an old version of the page in your browser cache?

Hmm, indeed.  I tried to refresh page before, but only this time with luck.

Anyway, broken links still here, functions gallery - just an example.  Feel free to reopen, if you think it's an issue.
