### ISSUE TITLE
Wrong answers from trigonometry functions of large arg

### ISSUE THREAD

**Issue by skirpichev** [fredrik-johansson/mpmath#372]
Docs says "Functions for evaluation of transcendental functions ... usually automatically increase the working precision and use a stricter tolerance to give a correctly rounded result with high probability ... It can often be assumed that such functions return values that have full accuracy, given inputs that are exact"

Unless I misunderstand something, when it (not often ?!:)) it can't be assumed - you have a bug.  Right?

Here is an example:
```
>>> import mpmath
>>> mpmath.sin(mpmath.e*10**100)
mpf('0.54341249980066286')
```

Both [diofant](https://github.com/diofant/diofant/blob/master/diofant/core/evalf.py#L640) and sympy have implemented heuristics to get right digits here, but I'm not sure if it's a correct place.

**Comment by fredrik-johansson** [comment]
That's not a valid example, because the input is not exactly 10^100 e but the exact rational number 3498128064099347 * 2^282.

**Comment by skirpichev** [comment]
So, mpmath.e for mpmath is not exact input (how we might guess looking on it's type), but just an approximation with default prec?  Then, indeed, there is no issue.
