### ISSUE TITLE
mp.mpf(numpy.int64(1)) fails with Python 3

### ISSUE THREAD

**Issue by nschloe** [fredrik-johansson/mpmath#382]
```python
from mpmath import mp
import numpy

mp.sqrt(numpy.int64(1))
```
fails with
```
TypeError: cannot create mpf from 1
```
under Python 3 (not 2). A similar bug exists in sympy, https://github.com/sympy/sympy/issues/13618.

**Comment by warnerjon12** [comment]
Finished and pushed. Pull request in.

**Comment by warnerjon12** [comment]
I am reorganizing my branches, will put in a new pull request for this shortly.
