### ISSUE TITLE
There are problems with integrating the gamma function

### ISSUE THREAD

**Issue by ghost** [fredrik-johansson/mpmath#384]
I was using SymPy and tried to numerically integrate the gamma function between 0 and 1 and between 1 and infinity, it didn't go well
SymPy uses mpmath for this calculation

normalhuman wrote that quadts is being used
```
>>> mp.quadts(lambda x: gamma(x), (0, 1))
mpf('43.843752231685052')
```

https://github.com/sympy/sympy/issues/14153

**Comment by warnerjon12** [comment]
Yes, indeed both of those integrals should diverge but from 0 to 1 it gives a smallish value. For the other one it does give a rather large value, indicating divergence, but from 0 to 1 is an issue.
