### ISSUE TITLE
mpmath is abandoned?

### ISSUE THREAD

**Issue by skirpichev** [fredrik-johansson/mpmath#399]
Sorry, @fredrik-johansson, it looks to be so.  If you more like "friendly and welcoming" communities like SymPy, instead of [simple policy](f86f108), maybe you can invite someone from that project to help you with maintenance?  After all, mpmath is a strict dependence for them too.  Beware, now they sometimes "fix" issues by removing them, but even this - a lot better then a dead project.

**Comment by fredrik-johansson** [comment]
No need to be sorry for asking a good question!

It's not dead, it's just resting ;-)

I have a long backlog of other work I have to do and this leads me to work on mpmath in batch mode with months of inactivity in between, unless some really urgent issue crops up. One such issue is #398, but it was submitted while I was in the middle of two weeks of conference travel in the US and other things just got in the way.

I am finally on vacation for a whole month starting today and will have definitely have time for a bit of mpmath development during this period, starting with immediately merging the open pull requests.

It's very discouraging for contributors when pull requests sit idle for months, I know!

I would happily accept the assistance if SymPy contributors wanted to help out more with mpmath, but as long as mpmath mostly "just works", I don't think there's going to be much interest, and other people have busy lives too.

**Comment by skirpichev** [comment]
> I have a long backlog of other work

Sure, I assume something like this.

> I would happily accept the assistance if SymPy contributors wanted to help out more with mpmath

@asmeurer, what do you think?

It would be a little discouraging for me, if this project adopts SymPy CoC practice.  But even this is better then a dead project.

> but as long as mpmath mostly "just works"

If you take look on your issue tracker, you will see - well, sometimes it doesn't.  And some issues come from SymPy.  Also, you have poor code coverage (#323), especially for docstrings.

So, if nobody from mentioned project will wiling to help you, @fredrik-johansson, please consider formalizing something like https://github.com/domgetter/NCoC policy.  In this case I'll try to help.

**Comment by asmeurer** [comment]
@skirpichev numerical algorithms are not my forte. I do submit bugfixes from time to time. For the most part mpmath is quite stable and we see very few bugs from it in SymPy. Some better algorithms in some places would be nice, but, again, I'm probably not the best person to do this. The primary issue I'm aware of is that numerical integration can be very slow, but I'm not even sure if this is mpmath's fault or SymPy's, as I've never dug into it. 

If there's a list of major things that still remain to be done for mpmath, we can link to them from our [roadmap](http://www.sympy.org/en/roadmap.html) and/or [GSoC ideas](https://github.com/sympy/sympy/wiki/GSoC-2018-Ideas) pages.

**Comment by skirpichev** [comment]
> @skirpichev numerical algorithms are not my forte.

I'm not asking you personally, but as a project leader.  Maybe someone else from sympy could help?

> If there's a list of major things that still remain to be done for mpmath

There are bugs to handle.  Could you fix this?  (Optimally, with patches, not by removing issues.)  There are pull requests to review.  Could someone do review?

**Comment by asmeurer** [comment]
I have no control over what other members of the SymPy community spend their time on. Everyone on the project is a volunteer. The best I can do is if something is on the roadmap or GSoC list then we might be able to get funding for it, but that's primarily for major things. There are also things like the NumFOCUS grants which could be used for bug fixing, but again, first you have to find someone interested.

**Comment by kagalenko-m-b** [comment]
I would like to draw attention to issue #388 . This is really insidious bug, it silently gives results that are 100% wrong.

**Comment by skirpichev** [comment]
@fredrik-johansson, why this was closed?

**Comment by fredrik-johansson** [comment]
It seemed to be... abandoned :)
