### ISSUE TITLE
UnboundLocalError in findroot

### ISSUE THREAD

**Issue by skirpichev** [fredrik-johansson/mpmath#401]
This is a reproducible scenario, that was triggered in the Diofant.

```
>>> import mpmath
>>> with mpmath.workprec(2):
...     mpmath.findroot(lambda x: x**2 - 4456178*x + 60372201703370, mpmath.mpc(real='5.278e+13', imag='-5.278e+13'))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/sk/venv/dev/lib/python3.5/site-packages/mpmath/calculus/optimization.py", line 967, in findroot
    if not isinstance(x, (list, tuple, ctx.matrix)):
UnboundLocalError: local variable 'x' referenced before assignment
```

**Comment by skirpichev** [comment]
Wow.  This trivial problem was workarounded in SymPy two years ago: https://github.com/sympy/sympy/commit/ed1d99f5904b90bab3f28cdc546c019c0e3b7ac0 instead of being solved.

And, sorry, perhaps it's a duplicate bugreport, see #192, #387 and #143.  But who cares, anyway.

**Comment by warnerjon12** [comment]
Just fixed, will make a pull request. It now checks for empty iterations and raises ValueError instead.
