### ISSUE TITLE
Enhancement request: add the function log1p

### ISSUE THREAD

**Issue by WarrenWeckesser** [fredrik-johansson/mpmath#420]
The function `log1p(x)` is simply `log(1 + x)`, but it avoid the loss of precision that occurs in the naive implementation when x is very small.  For example,

```
In [1]: import mpmath

In [2]: mpmath.mp.dps = 15

In [3]: x = mpmath.mpf('5e-17')
```
The following should be approximately 5e-17:

```
In [4]: mpmath.log(1 + x)
Out[4]: mpf('0.0')
```
Both NumPy and the standard `math` library  have implementations of `log1p`, e.g.:

```
In [5]: import numpy as np

In [6]: np.log1p(float(x))
Out[6]: 5e-17
```
`log1p` is the inverse of `expm1`, and `mpmath` already has `expm1`, so I don't think `log1p` is out of scope for `mpmath`.

**Comment by fredrik-johansson** [comment]
I've wanted this too. Done.

**Comment by WarrenWeckesser** [comment]
Great, thanks!
