### ISSUE TITLE
Restore Python 3.4 support?

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/mpmath#434]
We just dropped Python 3.4 support since Travis was having issues with it, but a user has pointed out in private communication that mpmath is being actively used in some environments that only have Python 3.4. We shouldn't need any Python >= 3.5 features, so it's just a question of testing compatibility.

**Comment by asmeurer** [comment]
What environments only have 3.4? For SymPy, we drop Python version support when CPython does https://github.com/sympy/sympy/wiki/Python-version-support-policy. For 3.4, the end of life is [in about a month](https://devguide.python.org/#status-of-python-branches) (we plan the next release of SymPy, hopefully in the next month, to be the last version to support 3.4).

**Comment by skirpichev** [comment]
For record, support of CPython 3.4 was removed [here](#432) with the [explanation](https://github.com/fredrik-johansson/mpmath/pull/432#issuecomment-460073195).  There are some random failures while upgrading setuptools and that happens only on CPython 3.4.

**Comment by fredrik-johansson** [comment]
> What environments only have 3.4?

Apparently, some legacy systems where upgrading isn't an option -- Windows XP in particular.

**Comment by asmeurer** [comment]
From a technical standpoint you gain little from dropping 3.4 support as long as you suppprt Python 2. The main advantage is one less build in the CI build matrices (a big deal for sympy but maybe not so much for mpmath).

**Comment by skirpichev** [comment]
> Windows XP in particular.

Hmm, why on Windows XP can't be installed something different from CPython 3.4?!

> From a technical standpoint you gain little from dropping 3.4 support

Are you willing to invest your time in debugging mentioned above setuptools-related issue?  And there may be more: every major CPython release has incompatibilities with older versions.
