### ISSUE TITLE
Practical usage of rounding complex number

### ISSUE THREAD

**Issue by nagayev** [fredrik-johansson/mpmath#447]
Hello.
I want to add methods for flooring, ceiling and rounding complex number to std Python library,
[https://bugs.python.org/issue36228](bpo-36228).
And Tim Peters said you are author of this library and you can help me with practical usage of complex numbers.

**Comment by fredrik-johansson** [comment]
Thanks, I commented over there.

**Comment by nagayev** [comment]
@nagayev Thanks.
