### ISSUE TITLE
Error estimate for Durand Kerner method (function polyroots) 

### ISSUE THREAD

**Issue by vdbergh** [fredrik-johansson/mpmath#460]
The current estimate for the error of a root (the absolute value of the last update, let's call the latter "`delta`") is not quite theoretically correct. It should be `(degree-1)*abs(delta)`. See for example

https://en.wikipedia.org/wiki/Durand%E2%80%93Kerner_method#Root_inclusion_via_Gerschgorin's_circles

**Comment by vdbergh** [comment]
I also wonder if there would be some interest determining the required extra precision automatically. This is quite easy but requires some code

1. The roots which are mathematically zero should be factored out (one cannot talk about the relative error of a quantity which is zero).
2. The precision loss of the update step should be estimated. This is standard floating point stuff.

I have actually code that does this for my own DK implementation. I could port it.

**Comment by vdbergh** [comment]
Actually perhaps I was too hasty. It appears that if the roots are simple and the updates have become sufficiently small then there is a much stronger bound on the error than the one I mentioned in the opening post

https://en.wikipedia.org/wiki/Durand%E2%80%93Kerner_method#Convergence_results

(it seems less clear to me what happens with multiple roots).

**Comment by vdbergh** [comment]
Well it seems that is there is no obviously best procedure for obtaining root enclosures. See e.g.

https://core.ac.uk/download/pdf/82541179.pdf
https://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=E42B3266706BA4DED7A018DD32EBBBDA?doi=10.1.1.53.7516&rep=rep1&type=pdf

In general one would want to use a mixture of bounds and some interval arithmetic.

But I would say that in multi precision arithmetic getting the best possible bounds, which would need quite obscure code to cover all cases, is not very important as one can always do a few extra iteration steps with the appropriate precision to bring the root estimates within the prescribe tolerance.

**Comment by fredrik-johansson** [comment]
Thanks for the input. There are definitely many ways that this code could be improved!
