### ISSUE TITLE
[Python3.8] SyntaxWarning

### ISSUE THREAD

**Issue by sheerluck** [fredrik-johansson/mpmath#477]
mpmath/ctx_mp_python.py:892: SyntaxWarning: "is" with a literal. Did you mean "=="?
mpmath/ctx_mp_python.py:986: SyntaxWarning: "is" with a literal. Did you mean "=="?

**Comment by cclauss** [comment]
Can this be closed?  Automatic discovery of these can be achieved by: __flake8 . --select=F632__

These instances must have been fixed or they would appear in
https://travis-ci.org/fredrik-johansson/mpmath/jobs/617056073#L246
