### ISSUE TITLE
mpmath creates Memory Error on import

### ISSUE THREAD

**Issue by brianmcconnel** [fredrik-johansson/mpmath#513]
I wasn't able to determine the reason, but it seems that when importing mpmath with gmp=6.2.0 it creates a Memory Error during this operation:

mpmath/mpmath/libmp/libelefun.py
```
# ~= next power of two + 20
cache_prec_steps = [22,22]
for k in xrange(1, bitcount(LOG_TAYLOR_PREC)+1):
cache_prec_steps += [min(2**k,LOG_TAYLOR_PREC)+20] * 2**(k-1)
```

When I downgraded gmp<=6.1.2.

mpmath imported successfully.

Stack trace is unavailable.  If I am able to reproduce behavior I will attach.

python 3.7.6
gmpy2 2.1.0b1

**Comment by brianmcconnel** [comment]
Running on CENTOS 7, I assume this is also a problem on REDHAT and Amazon Linux2.  Was not able to reproduce on Debian distro.

$  conda create -n mpmath -c conda-forge python=3.7 mpmath gmpy2 gmp=6.2.0
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/bmcconnel/miniconda3/envs/mpmath     
  added / updated specs:
    - gmp=6.2.0
    - gmpy2
    - mpmath
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            0_gnu         435 KB  conda-forge
    ca-certificates-2019.11.28 |       hecc5488_0         145 KB  conda-forge
    certifi-2019.11.28         |           py37_0         148 KB  conda-forge
    gmp-6.2.0                  |       he1b5a44_0         807 KB  conda-forge
    gmpy2-2.1.0b1              |   py37h04dde30_0         205 KB  conda-forge
    ld_impl_linux-64-2.33.1    |       h53a641e_7         653 KB  conda-forge
    libffi-3.2.1               |    he1b5a44_1006          46 KB  conda-forge
    libgcc-ng-9.2.0            |       h24d8f2e_2         8.2 MB  conda-forge
    libgomp-9.2.0              |       h24d8f2e_2         816 KB  conda-forge
    libstdcxx-ng-9.2.0         |       hdf63c60_2         4.5 MB  conda-forge
    mpc-1.1.0                  |    h04dde30_1006         149 KB  conda-forge
    mpfr-4.0.2                 |       he80fd80_0         673 KB  conda-forge
    mpmath-1.1.0               |             py_0         432 KB  conda-forge
    ncurses-6.1                |    hf484d3e_1002         1.3 MB  conda-forge
    openssl-1.1.1d             |       h516909a_0         2.1 MB  conda-forge
    pip-20.0.1                 |           py37_0         1.9 MB  conda-forge
    python-3.7.6               |       h357f687_2        52.9 MB  conda-forge
    readline-8.0               |       hf8c457e_0         441 KB  conda-forge
    setuptools-45.1.0          |           py37_0         648 KB  conda-forge
    sqlite-3.30.1              |       hcee41ef_0         2.0 MB  conda-forge
    tk-8.6.10                  |       hed695b0_0         3.2 MB  conda-forge
    wheel-0.33.6               |           py37_0          35 KB  conda-forge
    xz-5.2.4                   |    h14c3975_1001         366 KB  conda-forge
    zlib-1.2.11                |    h516909a_1006         105 KB  conda-forge
    ------------------------------------------------------------                                              Total:        82.0 MB   
The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu   ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py37_0
  gmp                conda-forge/linux-64::gmp-6.2.0-he1b5a44_0      gmpy2              conda-forge/linux-64::gmpy2-2.1.0b1-py37h04dde30_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  mpc                conda-forge/linux-64::mpc-1.1.0-h04dde30_1006   mpfr               conda-forge/linux-64::mpfr-4.0.2-he80fd80_0     mpmath             conda-forge/noarch::mpmath-1.1.0-py_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  pip                conda-forge/linux-64::pip-20.0.1-py37_0         python             conda-forge/linux-64::python-3.7.6-h357f687_2   readline           conda-forge/linux-64::readline-8.0-hf8c457e_0   setuptools         conda-forge/linux-64::setuptools-45.1.0-py37_0  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0      wheel              conda-forge/linux-64::wheel-0.33.6-py37_0       xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001    zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Proceed ([y]/n)? y


Downloading and Extracting Packages
_libgcc_mutex-0.1    | 3 KB      | ######################## | 100% setuptools-45.1.0    | 648 KB    | ######################## | 100% tk-8.6.10            | 3.2 MB    | ######################## | 100% ca-certificates-2019 | 145 KB    | ######################## | 100% mpc-1.1.0            | 149 KB    | ######################## | 100% ld_impl_linux-64-2.3 | 653 KB    | ######################## | 100% libstdcxx-ng-9.2.0   | 4.5 MB    | ######################## | 100% gmpy2-2.1.0b1        | 205 KB    | ######################## | 100% sqlite-3.30.1        | 2.0 MB    | ######################## | 100% ncurses-6.1          | 1.3 MB    | ######################## | 100% gmp-6.2.0            | 807 KB    | ######################## | 100% certifi-2019.11.28   | 148 KB    | ######################## | 100% mpfr-4.0.2           | 673 KB    | ######################## | 100% openssl-1.1.1d       | 2.1 MB    | ######################## | 100% readline-8.0         | 441 KB    | ######################## | 100% _openmp_mutex-4.5    | 435 KB    | ######################## | 100% zlib-1.2.11          | 105 KB    | ######################## | 100% libffi-3.2.1         | 46 KB     | ######################## | 100% libgomp-9.2.0        | 816 KB    | ######################## | 100% mpmath-1.1.0         | 432 KB    | ######################## | 100% libgcc-ng-9.2.0      | 8.2 MB    | ######################## | 100% python-3.7.6         | 52.9 MB   | ######################## | 100% xz-5.2.4             | 366 KB    | ######################## | 100% wheel-0.33.6         | 35 KB     | ######################## | 100% pip-20.0.1           | 1.9 MB    | ######################## | 100% Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mpmath
#
# To deactivate an active environment, use
#
#     $ conda deactivate

 $  conda activate mpmath
 $  python
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpmath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/$HOME/miniconda3/envs/mpmath/lib/python3.7/site-packages/mpmath/__init__.py", line 5, in <module>
    from .ctx_fp import FPContext
  File "/home/$HOME/miniconda3/envs/mpmath/lib/python3.7/site-packages/mpmath/ctx_fp.py", line 1, in <module>
    from .ctx_base import StandardBaseContext
  File "/home/$HOME/miniconda3/envs/mpmath/lib/python3.7/site-packages/mpmath/ctx_base.py", line 3, in <module>
    from .libmp.backend import xrange
  File "/home/$HOME/miniconda3/envs/mpmath/lib/python3.7/site-packages/mpmath/libmp/__init__.py", line 17, in <module>
    from .libmpc import (mpc_one, mpc_zero, mpc_two, mpc_half,       File "/home/$HOME/miniconda3/envs/mpmath/lib/python3.7/site-packages/mpmath/libmp/libmpc.py", line 23, in <module>
    from .libelefun import (\
  File "/home/$HOME/miniconda3/envs/mpmath/lib/python3.7/site-packages/mpmath/libmp/libelefun.py", line 76, in <module>
    cache_prec_steps += [min(2**k,LOG_TAYLOR_PREC)+20] * 2**(k-1)  MemoryError

**Comment by brianmcconnel** [comment]
Does this matter to anyone?  Seems like a bit dangerous operation to have right at import.  Also there isn't a good error message or trail of breadcrumbs to lead a developer to a solution.

**Comment by tjb900** [comment]
I've just hit this also; looks like a broken gmp package in `conda-forge`.  That loop is supposed to stop at about k=12 (AFAICT this is what `bitcount` calls, in `libintmath.py`):

```
>>> import gmpy2 as gmpy
>>> gmpy.mpz(2500).num_digits(2)
12
```

but with gmp==6.2.0 from conda-forge (`conda-forge/linux-64::gmp-6.2.0-he1b5a44_0`), this happens 

```
>>> import gmpy2 as gmpy
>>> gmpy.mpz(2500).num_digits(2)
53
```

and so the code snippet above goes on to try and create a list of length 2**52 or so.

**Comment by ngoldbaum** [comment]
I opened https://github.com/conda-forge/gmp-feedstock/issues/17 which will hopefully get the attention of the conda-forge maintainers.

**Comment by isuruf** [comment]
I can't reproduce this. What's your CPU model?

**Comment by isuruf** [comment]
Also, try running the following C program,
```C
#include <gmp.h>
#include <stdio.h>

int main() {
  mpz_t m;
  mpz_init_set_si(m, 2500);
  size_t d = mpz_sizeinbase(m, 2);
  printf("%ld\n", d);
  mpz_clear(m);
}
```

**Comment by tjb900** [comment]
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 44
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
stepping        : 2
microcode       : 0x1a
cpu MHz         : 1729.000
cache size      : 12288 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm epb tpr_shadow vnmi flexpriority ept vpid dtherm ida arat
bogomips        : 5327.73
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

The C code snippet above also outputs 53 when using the library from the 6.2.0 build:

```
# 6.1.2
(mpmath_debug) xxx$ LD_LIBRARY_PATH=xxx/envs/mpmath_debug2/lib ./testmp
12
# 6.2.0
(mpmath_debug) xxx$ LD_LIBRARY_PATH=xxx/envs/mpmath_debug/lib ./testmp
53
```

And interestingly:

```
(mpmath_debug) xxx$ python -c "import gmpy2 as gmpy; print(gmpy.mpz(2500));"
Illegal instruction
```

**Comment by isuruf** [comment]
@tjb900, can you report this to the GMP mailing list? https://gmplib.org/manual/Reporting-Bugs.html (There are some information required mentioned in the page above when making a bug report)

Can you also try building GMP from source and installing it into the conda environment? Here are the options we use to build GMP https://github.com/conda-forge/gmp-feedstock/blob/master/recipe/build.sh.

**Comment by ngoldbaum** [comment]
I can't reproduce this either on a AMD Ryzen 2970WX. If anyone has an intel CPU (particularly a westmere one like @tjb900) it would be great if you could reproduce this and report it upstream.

**Comment by jjhelmus** [comment]
On a Wolfdale processor:

```
(base) jhelmus@geezer:~$ lscpu 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               23
Model name:          Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
Stepping:            10
CPU MHz:             1994.972
CPU max MHz:         3000.0000
CPU min MHz:         1998.0000
BogoMIPS:            5984.79
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            6144K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority dtherm
```

I'm seeing the same behavior as @tjb900  from the test program:

```
(mpmath_dev_620) jhelmus@geezer:~$ $CC -I ${CONDA_PREFIX}/include/ -L ${CONDA_PREFIX}/lib -l gmp ~/test.c 
(mpmath_dev_620) jhelmus@geezer:~$ ./a.out 
53
(mpmath_dev_612) jhelmus@geezer:~$ $CC -I ${CONDA_PREFIX}/include/ -L ${CONDA_PREFIX}/lib -l gmp ~/test.c 
(mpmath_dev_612) jhelmus@geezer:~$ ./a.out 
12
```

The 6.2.0 package does produce an illegal instruction, 6.1.2 does not:
```
(mpmath_dev_620) jhelmus@geezer:~$ python -c "import gmpy2 as gmpy; print(gmpy.mpz(2500));"
Illegal instruction (core dumped)
(mpmath_dev_612) jhelmus@geezer:~$ python -c "import gmpy2 as gmpy; print(gmpy.mpz(2500));"
2500
```

**Comment by jjhelmus** [comment]
Build `gmp` package from the conda-forge recipe on the E8400 machine produces a package that gives the expected results:

```
(mpmath_dev_local) jhelmus@geezer:~$ $CC -I ${CONDA_PREFIX}/include/ -L ${CONDA_PREFIX}/lib -l gmp ~/test.c
(mpmath_dev_local) jhelmus@geezer:~$ ./a.out
12
(mpmath_dev_local) jhelmus@geezer:~$ python -c "import gmpy2 as gmpy; print(gmpy.mpz(2500));"
2500
```

**Comment by jjhelmus** [comment]
For reference here is the build log for gmp: [gmp_build_log.tar.gz](https://github.com/fredrik-johansson/mpmath/files/4135621/gmp_build_log.tar.gz)

**Comment by isuruf** [comment]
This was an issue with how we were building GMP at conda-forge and has been fixed now. Updating gmp should fix this issue.

**Comment by jjhelmus** [comment]
I can confirm that the 6.2.0 build 1 packages (conda-forge/linux-64::gmp-6.2.0-he1b5a44_1) give the expect results for the test program and the python test.

**Comment by brianmcconnel** [comment]
I can also confirm that this now works after updating to the latest version of gmp=6.2.0
gmp                       6.2.0                he1b5a44_1    conda-forge

I was able to get it to work on two intel cpus:
An old Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz
And a newer Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz

Thanks for the help in getting to the bottom of the issue.
