### ISSUE TITLE
codecov.io shows strange coverage

### ISSUE THREAD

**Issue by MaxGaukler** [fredrik-johansson/mpmath#530]
This screenshot from https://codecov.io/gh/fredrik-johansson/mpmath/src/8eae5da064603f1f871bb8c33eb2bba22b3f5b19/mpmath/matrices/matrices.py#L946
shows weird coverage annotations that make no sense:

![screenshot](https://user-images.githubusercontent.com/21340673/77320422-d5acd700-6d10-11ea-824d-6ce1137b38ed.png)

Something may be wrong with the collection or parsing of coverage data.

**Comment by skirpichev** [comment]
Any other example?  That might be a glitch on the codecov side.

**Comment by MaxGaukler** [comment]
I couldn't find an example on the current master branch - closing.
