### ISSUE TITLE
Digamma function of certain complex values does not converge

### ISSUE THREAD

**Issue by ribault** [fredrik-johansson/mpmath#534]
The function digamma(z) = psi(0, z) does not seem to converge if the real part of z is less than -1/2: the calculation keeps running without giving an answer.

**Comment by paulmasson** [comment]
@ribault could you give some explicit examples? I'm not seeing any issues with `digamma` on the complex plane.

**Comment by ribault** [comment]
The issue arises with higher precision, if you declare 'mp.dps = 30' for example.

In this example I did a keyboard interrupt when the evaluation of the digamma function did not seem to converge. Contrary to my first message, the critical value of the real part of z does not seem to be -1/2, and may depend on mp.dps. 

[Digamma_example.ipynb.gz](https://github.com/fredrik-johansson/mpmath/files/4841898/Digamma_example.ipynb.gz)

**Comment by paulmasson** [comment]
@fredrik-johansson I can confirm that `digamma` is hanging for higher precision in various ranges. Setting `mp.dps=30`, `digamma(-.75+.1j)` does not complete evaluation after 30 seconds, while `digamma(-.74+.1j)` returns immediately. Setting `mp.dps=16` returns immediately for `digamma(-.75+.1j)` while with `mp.dps=17` the evaluation again hangs. With this last precision the evaluation begins to hang at `digamma(-.46+.1j)`.

@ribault error is clearly dependent on `mp.dps`.

**Comment by fredrik-johansson** [comment]
Should be fixed now.
