### ISSUE TITLE
old warnings, release?

### ISSUE THREAD

**Issue by nschloe** [fredrik-johansson/mpmath#547]
I'm getting warnings concerning fixes that are 16 months old:

https://github.com/fredrik-johansson/mpmath/commit/4990fb5cf3447b956e87bf060420a296b13cedb1#diff-550b6d03e9982886a0afe0a8e1e4010d

Perhaps a release is in order?

**Comment by fredrik-johansson** [comment]
Yes. I'll try to find some time for working on mpmath.

**Comment by nschloe** [comment]
I'd probably just try to get a shorter release pipeline. You already got tests in order, which is is great. If you get an idea of the coverage and if that's reasonably high, this can give you some confidency to [rero](https://en.wikipedia.org/wiki/Release_early,_release_often).

**Comment by nschloe** [comment]
1.2.1 released, https://pypi.org/project/mpmath/#history.
