### ISSUE TITLE
setuptools_scm dropped Python 2 breaking install

### ISSUE THREAD

**Issue by mikedh** [fredrik-johansson/mpmath#580]
Thanks for the great project! 

It unfortunately looks like [setuptools_scm dropped support for Python 2](https://github.com/pypa/setuptools_scm/issues/541), which appears to have broken the install for mpmath on Python 2. Here's a [broken CI run](https://github.com/mikedh/trimesh/pull/1182/checks?check_run_id=2135678957) demonstrating the issue.

**Comment by asmeurer** [comment]
I [warned](https://github.com/fredrik-johansson/mpmath/issues/443) that using setuptools_scm was problematic. 

It does seem odd though. Shouldn't setuptools_scm be using the python_requires feature that prevents non-Python 2 compatible versions from being installed in Python 2?

**Comment by skirpichev** [comment]
> I warned that using setuptools_scm was problematic.

versioneer also [drops](https://github.com/python-versioneer/python-versioneer/commit/25cabf62e51edc4d7793f3e273729b8c10e0ec0f) Py2.

> Shouldn't setuptools_scm be using the python_requires feature

Other suggestions?  Given that setuptools_scm will not work on py2...

PS: Conditional dependency on setuptools_scm [should work](https://github.com/fredrik-johansson/mpmath/pull/581#issuecomment-806367566).

**Comment by asmeurer** [comment]
versioneer doesn't create a dependency. It installs a completely self contained script into the repository. Issues like this are impossible with it.

**Comment by skirpichev** [comment]
> It installs a completely self contained script

That reminds me pytest's runtests.py.  Yes, issues like this are impossible.  Others are.

**Comment by fredrik-johansson** [comment]
Are there any objections to simply dropping Python 2 at this point?

**Comment by skirpichev** [comment]
@fredrik-johansson, I think, e.g. @asmeurer (I don't know any schedule for dropping py2 in sympy) will disagree and @mikedh as well.

It's possible to make a dedicated branch, e.g. 1.2.x, that will keep support for py2.   Backport fixes, maybe even features.  But it's hard, given [this](https://groups.google.com/g/sympy/c/dRzAOoi1B0Q) and/or #550.

It's possible to check dependents, how many do support py2:
https://libraries.io/pypi/mpmath/dependents
(not sure how complete this list is)

**Comment by skirpichev** [comment]
Oh, I miss that setuptools_scm-based setup was broken by 867d8784.  Probably, this was the reason for #585.

Either this commit must be reverted (and then you can apply #583 to solve py2 problem).  Or we could revert setuptools_scm properly to use old scheme for version management (i.e. `__version__` specified by hand): #586.

**Comment by asmeurer** [comment]
SymPy hasn't supported Python 2 for over a year. I would support dropping it in mpmath, especially if active development is being done on it.
