### ISSUE TITLE
Is there a reason to use pylab instead of pyplot?

### ISSUE THREAD

**Issue by PyGamer0** [fredrik-johansson/mpmath#623]
I can't use pylab due to import errors. Is there a reason why mpmath uses pylab instead of pyplot?

pylab also requires `numpy` as a dependency.

Ref: https://stackoverflow.com/questions/16849483/which-is-the-recommended-way-to-plot-matplotlib-or-pylab

**Comment by oscarbenjamin** [comment]
The pyplot module in matplotlib still depends on numpy because matplotlib depends on numpy.

I don't think that mpmath's use of pylab should cause any import errors (unless you have made a file called pylab.py in the current directory).

**Comment by PyGamer0** [comment]
@oscarbenjamin I get a ModuleNotFound error, it says `kiwisolver`, but when I run `pip install kiwisolver`, it says it's present?!

**Comment by oscarbenjamin** [comment]
This just sounds like a problem with your Python installation rather than anything to do with mpmath.

**Comment by PyGamer0** [comment]
Closing, sorry for the clutter.
