### ISSUE TITLE
Results of trigonometric functions differ from standard math module for large numbers

### ISSUE THREAD

**Issue by IamMusavaRibica** [fredrik-johansson/mpmath#630]
```py
>>> from math import cos as math_cos
>>> from mpmath import cos as mp_cos
>>> a = 452175521116192774
>>> math_cos(a)
-0.26390487516327094
>>> mp_cos(a)
mpf('-0.5229034783961185')
>>> 
```
Why is this behaviour?
In math, cos(x) in radians should be the same as cos(x + 2pi)
However, results from the standard `math` module and `mpmath`'s cos functions differ when there is a large number
```py
>>> from math import cos, pi
>>> from mpmath import cos as mp_cos, pi as mp_pi
>>> cos(7)
0.7539022543433046
>>> cos(7 + 2*pi)
0.7539022543433048
>>> mp_cos(7)
mpf('0.7539022543433046')
>>> mp_cos(7 + 2*mp_pi)
mpf('0.75390225434330482')
>>> cos(452175521116192774)
-0.26390487516327094
>>> cos(452175521116192774 + 2*pi)
-0.26390487516327094
>>> mp_cos(452175521116192774)
mpf('-0.5229034783961185')
>>> mp_cos(452175521116192774 + 2*mp_pi)
mpf('-0.26390487516327094')      # notice it is different than the result above, and it is CORRECT, comparing to math.cos
```
Perhaps there is a mathematical reasoning?
I don't understand why does this happen

**Comment by MontyPythagoras** [comment]
As you can see here:
https://www.wolframalpha.com/input?i=cos%28452175521116192774.0%29
the value "-0.5229..." is correct. Therefore, mpmath yields the correct result.
The regular math module calculates with float numbers at double precision. The large number that you entered here has 18 digits and cannot be accurately represented as a float number. Hence, it is being rounded.

**Comment by IamMusavaRibica** [comment]
Thanks. This can be closed now. Also see : https://math.stackexchange.com/questions/4460646/why-do-different-calculators-disagree-on-cos452175521116192774
